version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
aliases:
  - &restore-cache
    restore_cache:
        key: full-cache-{{ checksum "package.json" }}-{{ checksum "integration/hello-world/package.json" }}-{{ checksum "integration/nestjs-application/package.json" }}
  - &install-deps
    run:
        name: Install dependencies
        command: npm ci
  - &build-packages
    run:
        name: Build packages
        command: npm run build:packages
  - &build-integration
    run:
        name: Build integration
        command: npm run build:integration
  - &run-unit-tests
    run:
        name: Run unit tests
        command: npm run test
  - &deploy-integration-tests-hello-world
    run:
        name: Deploy integration tests
        command: sh scripts/core.sh deploy hello-world infrastructure --outputs-file atlas-core-artifact.json && sh scripts/core.sh deploy hello-world application --outputs-file ./integration/hello-world/env.json
  - &run-integration-tests-hello-world
    run:
        name: Run Integration tests
        command: npm run test:integration
  - &destroy-integration-tests-hello-world
    run:
        name: Destroy integration tests
        command: yes | sh scripts/core.sh destroy hello-world application || true && yes | sh scripts/core.sh destroy hello-world infrastructure || true 

unit-tests-template: &unit-tests-template
  working_directory: ~/atlas
  steps:
    - checkout
    - *restore-cache
    - *install-deps
    - *build-packages
    - *run-unit-tests

jobs:
  build:
    working_directory: ~/atlas
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Update NPM version
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: full-cache-{{ checksum "package.json" }}-{{ checksum "integration/hello-world/package.json" }}-{{ checksum "integration/nestjs-application/package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build packages
          command: npm run build
      - save_cache:
          key: full-cache-{{ checksum "package.json" }}-{{ checksum "integration/hello-world/package.json" }}-{{ checksum "integration/nestjs-application/package.json" }}
          paths:
            - ./node_modules
            - ./integration/hello-world/node_modules/
            - ./integration/nestjs-application/node_modules/
        
  test_node_12:
    <<: *unit-tests-template
    docker:
      - image: circleci/node:12

  test_node_14:
    <<: *unit-tests-template
    docker:
      - image: circleci/node:14
    
  test_node_16:
    working_directory: ~/atlas
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - *build-packages
      - *run-unit-tests
      - run:
          name: Collect coverage
          command: npm run coverage
      - store_artifacts:
          path: coverage

  lint:
    working_directory: ~/atlas
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Lint commit
          command: ./node_modules/.bin/commitlint-circle -c .commitlintrc.json
  integration_build:
    working_directory: ~/atlas
    executor: aws-cli/default
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - *restore-cache
      - *build-integration
      - save_cache:
          key: integration_dist-{{ checksum "package.json" }}
          paths:
            - ./integration_dist
  integration_hello_world_deploy:
    working_directory: ~/atlas
    executor: aws-cli/default
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
      - *restore-cache
      - restore_cache:
          key: integration_dist-{{ checksum "package.json" }}
      - *deploy-integration-tests-hello-world
      - *run-integration-tests-hello-world
      - *destroy-integration-tests-hello-world
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test_node_16:
          requires:
            - build
      - test_node_14:
          requires:
            - build
      - test_node_12:
          requires:
            - build
      - lint:
          requires:
            - build
      - integration_build:
          requires:
            - build
      - integration_hello_world_deploy:
          requires:
            - integration_build
      # - samples:
      #     requires:
      #       - build